### PR TITLE
Dropping the .altinstr_replacement section from the toolchain

### PR DESCRIPTION
**Pull request by rbs-alexr**
- [X] I have reviewed the [OFRAK contributor guide](https://ofrak.com/docs/contributor-guide/getting-started.html) and attest that this pull request is in accordance with it.

**One sentence summary of this PR (This should go in the CHANGELOG!)**
We also want to drop the .altinstr_replacement section when we are performing patches

**Link to Related Issue(s)**

**Please describe the changes in your request.**
This PR adds .altinstr_replacement to the toolchain's linker section droplist

**Anyone you think should look at this, specifically?**
@rbs-afflitto also ran into this issue

### CODE REVIEW

**Comment by rbs-afflitto** [comment]
This looks good to me

**Comment by whyitfor** [comment]
This needs a Changelog entry for ofrak-patch-maker.

Probably can be considered a bugfix.

**Comment by whyitfor** [comment]
I'm curious what triggered discovery of this issue. Has it always been around, or is this something new? Did a change create it?

**Comment by rbs-alexr** [comment]
We observed this section when working on code for AARCH64 Linux 4

**Comment by rbs-alexr** [comment]
Pending further feedback, can we merge this in?

**Review by whyitfor — APPROVED** [review]
LGTM

**Pull request merged**
