### PR TITLE
Switch from Debian 11 to Debian 12

### PR DESCRIPTION
**Pull request by ANogin**
- [X] I have reviewed the [OFRAK contributor guide](https://ofrak.com/docs/contributor-guide/getting-started.html) and attest that this pull request is in accordance with it.

**One sentence summary of this PR (This should go in the CHANGELOG!)**
Changes the docker configuration to use Debian 12 Bookworm rather then Debian 11 Bullseye.

**Link to Related Issue(s)**
N/A

**Please describe the changes in your request.**
Changes the docker configuration to use Debian 12 Bookworm rather then Debian 11 Bullseye. This requires switching gcc-10 to gcc-12 for gcc installed from apt, and openjdk from 11 to 17.

**Anyone you think should look at this, specifically?**
@whyitfor

### CODE REVIEW

**Comment by ANogin** [comment]
All tests pass, except for one - `test_ofrak/components/test_elf_load_aligment_modifier.py::TestElfModifiers::test_elf_load_alignment_free_space_modifier[libc.so.6@debian-bullseye (with SCOP) ET_DYN Library]` which fails with when 
```
LD_PRELOAD=/tmp/ofrak_elf_modifier_out_vflqboxe/libc_elf_dyn_lib_aligned_free /ofrak_core/test_ofrak/components/assets/elf/echo_elf_dyn 'Hello world, echo!'
```
fails with
```
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!
```

**Comment by whyitfor** [comment]
What prompted this change?

**Comment by ANogin** [comment]
@whyitfor binary ninja no longer installs correctly in the default configuration :(
```
OSError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/rbs/binaryninja/python/binaryninja/../../libbinaryninjacore.so.1)
```
I am guessing they updated their build setup for a newer version of Linux?

**Comment by rbs-jacob** [comment]
Dan got the tests passing in the following branch. I have not yet reviewed the changes. 

<https://github.com/redballoonsecurity/ofrak/compare/master...Ivanov1ch:ofrak:feature/debian12>

**Comment by ANogin** [comment]
@rbs-jacob with DanI's change (a one-line change in `LD_PRELOAD` in testing) some other tests (specifically `notebooks_with_outputs` tests) still fail. Not sure though whether those test failures are actually meaningful...

**Comment by whyitfor** [comment]
@ANogin, do you plan on continuing to work on this PR? It not, this perhaps should become an issue.

A couple considerations:
- Ideally we can switch from Debian 11 to Debian 12 with minimal changes to the existing patch maker toolchains. Is it trivial to keep the existing toolchains (perhaps installing them from source)?
- Based on the discussion above, it seems that some test files might need to be rebuilt, or the tests need to be updated ("notebooks_with_outputs" tests will fail if any notebook output changes; it is likely that the expected notebook output needs to be reviewed and recommitted here)

**Comment by whyitfor** [comment]
Closing this PR, as #502 addresses the underlying issue.

**Pull request closed without merging**
